spring.main.web-application-type=none
spring.main.banner-mode=off

embabel.models.default-llm=gemini-2.5-flash

embabel.agent.platform.models.gemini.api-key=${GEMINI_API_KEY}

logging.level.root=WARN
logging.level.com.embabel=INFO
